# Generated by Django 5.2.6 on 2025-09-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(default='não definido', max_length=50),
            preserve_default=False,
        ),
    ]
